import Navigation from "./_component/Navigation";
import Logo from "./_component/Logo";
import "@/app/_styles/globals.css";

export const metadata = {
  title: "The Wild Oasis",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="bg-primary-950 text-primary-100 min-h-screen">
        <header>
          <Logo />
        </header>
        <Navigation />
        {children}
        <footer>Copyright by the wild oasis</footer>
      </body>
    </html>
  );
}
